blogpost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('subscribe/', include('marketing.urls', namespace='marketing')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketing/urls.py
from django.urls import path
from . import views

app_name = 'marketing'
urlpatterns = [
  path('', views.email_lists_signup, name='subscribe'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
  path('', views.index, name='index'),
  path('blog/', views.blog, name='blog'),
  path('post/<str:pk>/', views.post, name='post-detail'),
  path('post/create/', views.post_create, name='post-create'),
  path('post/<str:pk>/update/', views.post_update, name='post-update'),
  path('post/<str:pk>/delete/', views.post_delete, name='post-delete'),
  path('contact/', views.contact, name='contact'),
  path('search/', views.search, name='search'),
  path('accounts/register/', views.register_view, name='register'),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from tinymce import HTMLField

User = get_user_model()

class Author(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  profile_pic = models.ImageField()

  def __str__(self):
    return self.user.username


class Category(models.Model):
  title = models.CharField(max_length=20)

  def __str__(self):
    return self.title


class PostView(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  post = models.ForeignKey('Post', on_delete=models.CASCADE)

  def __str__(self):
    return self.user.username


class AnonymousView(models.Model):
  post = models.ForeignKey('Post', on_delete=models.CASCADE)

  def __str__(self):
    return self.post.title


class Comment(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  timestamp = models.DateTimeField(auto_now_add=True)
  post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
  content = models.TextField()
  
  def __str__(self):
    return self.user.username


class Post(models.Model):
  title = models.CharField(max_length=200)
  overview = models.TextField()
  author = models.ForeignKey(Author, on_delete=models.CASCADE)
  thumbnail = models.ImageField()
  categories = models.ManyToManyField(Category)
  previous_post = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='previous', null=True, blank=True)
  next_post = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='next', null=True, blank=True)
  content = HTMLField()
  timestamp = models.DateTimeField(auto_now_add=True)
  featured = models.BooleanField(default=True) 

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('posts:post-detail', kwargs={'pk': self.pk})

  def get_post_update(self):
    return reverse('posts:post-update', kwargs={'pk': self.pk})

  def get_post_delete(self):
    return reverse('posts:post-delete', kwargs={'pk': self.pk})

  @property
  def get_comments(self):
    return self.comments.all().order_by('-timestamp')

  @property
  def view_count(self):
    return PostView.objects.filter(post=self).count()

  @property
  def anonymous_view(self):
    return AnonymousView.objects.filter(post=self).count()

  @property
  def comment_count(self):
    return Comment.objects.filter(post=self).count()


class Contact(models.Model):
  username = models.CharField(max_length=100)
  email = models.EmailField()
  message = models.TextField()

  def __str__(self):
    return self.username

posts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from tinymce import TinyMCE 
from .models import Post, Comment, Contact


User = get_user_model()


class RegisterUser(UserCreationForm):
  username = forms.CharField(widget=forms.TextInput(attrs={
    'class': 'form-control',
    'placeholder': 'Username'
  }))
  email = forms.CharField(widget=forms.EmailInput(attrs={
    'class': 'form-control',
    'placeholder': 'someone@gmail.com'
  }))
  password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    'class': 'form-control',
    'placeholder': 'Password'
  }))
  password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    'class': 'form-control',
    'placeholder': 'Confirm Password'
  }))

  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']



class TinyMCEWidget(TinyMCE):
  def use_required_attribute(self, *args):
    return False


class PostForm(forms.ModelForm):
  content = forms.CharField(widget=TinyMCEWidget(attrs={
    'required': False,
    'cols': 30,
    'rows': 10
  }))

  class Meta:
    model = Post
    fields = ['title', 'overview', 'thumbnail', 'categories', 'previous_post', 'next_post', 'content', 'featured']


class CommentForm(forms.ModelForm):
  content = forms.CharField(widget=forms.Textarea(attrs={
    'class': 'form-control',
    'placeholder': 'Type your comment here',
    'id': 'usercomment',
    'rows': 4
  }))

  class Meta:
    model = Comment
    fields = ['content']

class ContactForm(forms.ModelForm):
  class Meta:
    model = Contact
    fields = '__all__'

posts/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from .models import Post, Author, PostView, AnonymousView
from .forms import CommentForm, PostForm, RegisterUser, ContactForm
from marketing.models import SignUp
from django.contrib import messages
from marketing.forms import EmailSignupForm


def register_view(request):
  if request.user.is_authenticated:
    return redirect("/")
  else:
    next = request.GET.get('next')
    form = RegisterUser(request.POST or None)
    if form.is_valid():
      form.save()
      if next:
        return redirect(next)
      return redirect('account_login')
    
    context = {
      'form': form
    }
    return render(request, 'register.html', context)


def get_author(user):
  qs = Author.objects.filter(user=user)
  if qs.exists():
    return qs[0]
  return None


def get_category_count():
  queryset = Post.objects.values('categories__title').annotate(Count('categories__title'))
  return queryset


def index(request):
  featured = Post.objects.filter(featured=True)
  latest = Post.objects.order_by('-timestamp')[0:3]
  form = EmailSignupForm()
  
  if request.method == 'POST':
    email = request.POST['email']
    new_email = SignUp()
    new_email.email = email
    new_email.save()
     
  context = {
    'object_list': featured,
    'latest': latest,
    'form': form
  }
  return render(request, 'index.html', context)


def blog(request):
  category_count = get_category_count()
  most_recent = Post.objects.order_by('-timestamp')[:3]
  post_list = Post.objects.all().order_by('id')
  paginator = Paginator(post_list, 4)
  page_request_var = 'page'
  page = request.GET.get(page_request_var)

  try:
    paginated_queryset = paginator.page(page)
  except PageNotAnInteger:
    paginated_queryset = paginator.page(1)
  except EmptyPage:
    paginated_queryset = paginator.page(paginator.num_pages)

  context = {
    'queryset': paginated_queryset,
    'page_request_var': page_request_var,
    'most_recent': most_recent,
    'category_count': category_count
  }
  return render(request, 'blog.html', context)


def post(request, pk):
  category_count = get_category_count()
  most_recent = Post.objects.order_by('-timestamp')[:3]
  post = get_object_or_404(Post, pk=pk)

  if request.user.is_authenticated:
    PostView.objects.get_or_create(user=request.user, post=post)
  else:
    AnonymousView.objects.get_or_create(post=post)

  form = CommentForm(request.POST or None)
  if request.method == 'POST':
    form.instance.user = request.user
    form.instance.post = post
    form.save()
    return redirect('posts:post-detail', pk=pk)

  context = {
    'form': form,
    'post': post,
    'most_recent': most_recent,
    'category_count': category_count
  }
  return render(request, 'post.html', context)


def search(request):
  queryset = Post.objects.all()
  query = request.GET.get('q')

  if query:
    queryset = queryset.filter(
      Q(title__icontains = query) |
      Q(overview__icontains = query)
    ).distinct()
  
  context = {
    'queryset': queryset
  }
  return render(request, 'search-result.html', context)


def post_create(request):
  form = PostForm(request.POST or None, request.FILES or None)
  author = get_author(request.user)
  if request.method == 'POST':
    if form.is_valid():
      form.instance.author = author
      form.save()
      return redirect('posts:post-detail', pk=form.instance.pk)
  context = {
    'form': form,
    'title': 'Create'
  }
  return render(request, 'post-create.html', context)


def post_update(request, pk):
  post = get_object_or_404(Post,pk=pk)
  form = PostForm(request.POST or None, request.FILES or None, instance=post)
  author = get_author(request.user)
  if request.method == 'POST':
    if form.is_valid():
      form.instance.author = author
      form.save()
      return redirect('posts:post-detail', pk=form.instance.pk)
  context = {
    'form': form,
    'title': 'Update'
  }
  return render(request, 'post-create.html', context)


def post_delete(request, pk):
  post = get_object_or_404(Post, pk=pk)
  post.delete()
  return redirect('posts:blog')

def contact(request):
  form = ContactForm(request.POST or None)
  if request.method == 'POST':
    if form.is_valid():
      form.save()
      form = ContactForm()
      messages.success(request, 'Your message has been sent')
    else:
      messages.warning(request, 'Please correct the errors below')

  context = {
    'form': form
  }
  return render(request, 'contact.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body>
  {% include 'header.html' %}

  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{message.tags}} text-center">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}

  {% block content %}
  {% endblock %}

  {% include 'footer.html' %}
  
  {% include 'scripts.html' %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row mt-5 mb-5">
      <div class="col-md-6 mx-auto">
        <div class="text-center">
          <h3>GET IN TOUCH</h3>
        </div>
        <form action="" method="POST">
          {% csrf_token %}
          {{form|crispy}}
          <button type="submit" class="btn btn-info">Submit</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/footer.html
{% load static %} 
 
 <!-- Page Footer-->
 <footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="logo">
          <h6 class="text-white">Sam's Tech Blog</h6>
        </div>
        <div class="contact-details">
          <p>Thika Superhighway, Nairobi, KE 00100</p>
          <p>Phone: (+254) 719-418-656</p>
          <p>Email: <a href="mailto:hnkhosamomollo@gmail.com">hnkhosamomollo@gmail.com</a></p>
          <ul class="social-menu">
            <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="menus d-flex">
          <ul class="list-unstyled">
            <li> <a href="#">My Account</a></li>
            <li> <a href="#">Add Listing</a></li>
            <li> <a href="#">Pricing</a></li>
            <li> <a href="#">Privacy &amp; Policy</a></li>
          </ul>
          <ul class="list-unstyled">
            <li> <a href="#">Our Partners</a></li>
            <li> <a href="#">FAQ</a></li>
            <li> <a href="#">How It Works</a></li>
            <li> <a href="#">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="latest-posts"><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image"><img src="{% static 'img/small-thumbnail-1.jpg' %}" alt="..." class="img-fluid"></div>
              <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
            </div></a><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image"><img src="{% static 'img/small-thumbnail-2.jpg' %}" alt="..." class="img-fluid"></div>
              <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
            </div></a><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image"><img src="{% static 'img/small-thumbnail-3.jpg' %}" alt="..." class="img-fluid"></div>
              <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
            </div></a></div>
      </div>
    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <p>&copy; 2020. All rights reserved. Sam's Tech Blog</p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/head.html
{% load static %}

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sam's Tech Blog</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="all,follow">
  <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome CSS-->
  <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
  <!-- Custom icon font-->
  <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
  <!-- Google fonts - Open Sans-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <!-- Fancybox-->
  <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <!-- Favicon-->
  <link rel="shortcut icon" href="{% static 'favicon.png' %}">
  <link rel="stylesheet" href="{% static 'css/github.css' %}">
  <!-- Tweaks for older IEs--><!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>

templates/header.html
<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn">
          <i class="icon-close"></i>
        </div>
        <div class="row d-flex justify-content-center">
          <div class="col-md-8">
            <form action="{% url 'posts:search' %}">
              <div class="form-group">
                <input type="search" name="q" id="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search-1"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <!-- Navbar Brand --><a href="{% url 'posts:index' %}" class="navbar-brand">Sam's Tech Blog</a>
        <!-- Toggle Button-->
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="{% url 'posts:index' %}" class="nav-link active ">Home</a>
          </li>
          <li class="nav-item"><a href="{% url 'posts:blog' %}" class="nav-link ">Blog</a>
          </li>
          <li class="nav-item"><a href="{% url 'posts:contact' %}" class="nav-link ">Contact</a>
          </li>
          {% if request.user.is_staff %}
          <li class="nav-item"><a href="{% url 'posts:post-create' %}" class="nav-link ">Create</a>
          </li>
          {% endif %}
        </ul>
        <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a>
        </div>
      </div>
    </div>
  </nav>
</header>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero Section-->
<section style="background: url({% static 'img/hero.jpg'%}); background-size: cover; background-position: center center"
  class="hero">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <h1>Get the Data Skills To Own The Future with Tech Knowledge</h1><a href="#" class="hero-link"></a>
      </div>
    </div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i> Scroll Down</a>
  </div>
</section>
<!-- Intro Section-->
<section class="intro">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h2 class="h3">Some great intro here</h2>
        <p class="text-big">Place a nice <strong>introduction</strong> here <strong>to catch reader's
            attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea
          commodo consequat. Duis aute irure dolor in reprehenderi.</p>
      </div>
    </div>
  </div>
</section>
<section class="featured-posts no-padding-top">
  <div class="container">
    <!-- Post-->
    {% for obj in object_list %}
    <div class="row d-flex align-items-stretch">
      {% if not forloop.first and not forloop.last %}
      <div class="image col-lg-5"><img src="{{ obj.thumbnail.url }}" alt="..."></div>
      {% endif %}
      <div class="text col-lg-7">
        <div class="text-inner d-flex align-items-center">
          <div class="content">
            <header class="post-header">
              <div class="category">
                {% for cat in obj.categories.all %}
                <a href="#">{{ cat.title }}</a>
                {% endfor %}
              </div>
              <a href="{{ obj.get_absolute_url }}">
                <h2 class="h4">{{ obj.title }}</h2>
              </a>
            </header>
            <p>{{ obj.overview }}</p>
            <footer class="post-footer d-flex align-items-center"><a href="#"
                class="author d-flex align-items-center flex-wrap">
                <div class="avatar"><img src="{{ obj.author.profile_pic.url }}" alt="..." class="img-fluid"></div>
                <div class="title"><span>{{ obj.author }}</span></div>
              </a>
              <div class="date"><i class="icon-clock"></i> {{ obj.timestamp|timesince }} ago</div>
              <div class="comments"><i class="icon-comment"></i>{{ obj.comment_count }}</div>
            </footer>
          </div>
        </div>
      </div>
      {% if forloop.first or forloop.last %}
      <div class="image col-lg-5"><img src="{{ obj.thumbnail.url }}" alt="..."></div>
      {% endif %}
    </div>
    {% endfor %}
    <!-- End Post -->
  </div>
</section>
<!-- Divider Section-->
<section style="background: url({% static 'img/divider-bg.jpg' %}); background-size: cover; background-position: center bottom"
  class="divider">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua</h2><a href="{% url 'posts:blog' %}" class="hero-link">View More</a>
      </div>
    </div>
  </div>
</section>
<!-- Latest Posts -->
<section class="latest-posts">
  <div class="container">
    <header>
      <h2>Latest from the blog</h2>
      <p class="text-big">Here are the latest posts form the blog</p>
    </header>
    <div class="row">
      {% for obj in latest %}
      <div class="post col-md-4">
        <div class="post-thumbnail">
          <a href="{{ obj.get_absolute_url }}">
            <img src="{{ obj.thumbnail.url }}" alt="..."
              class="img-fluid">
          </a>
        </div>
        <div class="post-details">
          <div class="post-meta d-flex justify-content-between">
            <div class="date">{{ obj.timestamp }}</div>
            <div class="category">
              {% for cat in obj.categories.all %}
              <a href="#">{{ cat }}</a>
              {% endfor %}
            </div>
          </div><a href="{{ obj.get_absolute_url }}">
            <h3 class="h4">{{ obj.title }}</h3>
          </a>
          <p class="text-muted">{{ obj.overview }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- Newsletter Section-->
<section class="newsletter no-padding-top">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Subscribe to Newsletter</h2>
        <p class="text-big">Subscribe to get the updates on when I'll be post new articles on the blog. I'll share some cool coding tips with you people.</p>
      </div>
      <div class="col-md-8">
        <div class="form-holder">
          <form action="{% url 'marketing:subscribe' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              {{form}}
              <button type="submit" class="submit">Subscribe</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Gallery Section-->
<section class="gallery no-padding">
  <div class="row">
    <div class="mix col-lg-3 col-md-3 col-sm-6">
      <div class="item"><a href="{% static 'img/gallery-1.jpg' %}" data-fancybox="gallery" class="image"><img
            src="{% static 'img/gallery-1.jpg' %}" alt="..." class="img-fluid">
          <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div>
        </a></div>
    </div>
    <div class="mix col-lg-3 col-md-3 col-sm-6">
      <div class="item"><a href="{% static 'img/gallery-2.jpg' %}" data-fancybox="gallery" class="image"><img
            src="{% static 'img/gallery-2.jpg' %}" alt="..." class="img-fluid">
          <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div>
        </a></div>
    </div>
    <div class="mix col-lg-3 col-md-3 col-sm-6">
      <div class="item"><a href="{% static 'img/gallery-3.jpg' %}" data-fancybox="gallery" class="image"><img
            src="{% static 'img/gallery-3.jpg' %}" alt="..." class="img-fluid">
          <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div>
        </a></div>
    </div>
    <div class="mix col-lg-3 col-md-3 col-sm-6">
      <div class="item"><a href="{% static 'img/gallery-4.jpg' %}" data-fancybox="gallery" class="image"><img
            src="{% static 'img/gallery-4.jpg' %}" alt="..." class="img-fluid">
          <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div>
        </a></div>
    </div>
  </div>
</section>
{% endblock %}

templates/post-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row">
      <main class="col-lg-6 mx-auto mt-3">
        <h3 class="display-6">{{title}} an article</h3>
        {{form.media}} 
        <form action="{% url 'posts:post-create' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </main>
    </div>
  </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto mt-5 mb-5">
      <h1>Sign Up</h1>

      <p>Already have an account? Then please <a href="{% url 'account_login' %}">sign in</a></p>

      <form class="signup" id="signup_form" method="post" action="{% url 'posts:register' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info mt-3" type="submit">Sign Up &raquo;</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/scripts.html
{% load static %}

<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
<script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>
<script src="{% static 'js/highlight.pack.js' %}"></script>
<script>hljs.initHighlightingOnLoad(); </script>

templates/sidebar.html
<aside class="col-lg-4">
  <!-- Widget [Search Bar Widget]-->
  <div class="widget search">
    <header>
      <h3 class="h6">Search the blog</h3>
    </header>
    <form action="{% url 'posts:search' %}" method="GET" class="search-form">
      <div class="form-group">
        <input type="text" name="q" placeholder="What are you looking for?">
        <button type="submit" class="submit"><i class="icon-search"></i>
        </button>
      </div>
    </form>
  </div>
  <!-- Widget [Latest Posts Widget]        -->
  <div class="widget latest-posts">
    <header>
      <h3 class="h6">Latest Posts</h3>
    </header>
    <div class="blog-posts">
      {% for post in most_recent %}
      <a href="{{ post.get_absolute_url }}">
        <div class="item d-flex align-items-center">
          <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
          <div class="title"><strong>{{ post.title }}</strong>
            <div class="d-flex align-items-center">
              {% if request.user.is_authenticated %}
              <div class="views">
                <i class="icon-eye"></i>{{ post.view_count }}
              </div>
              {% else %}
              <div class="views">
                <i class="icon-eye"></i>{{ post.anonymous_view }}
              </div>
              {% endif %}
              <div class="comments">
                <i class="icon-comment"></i>{{ post.comment_count }}
              </div>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
  <!-- Widget [Categories Widget]-->
  <div class="widget categories">
    <header>
      <h3 class="h6">Categories</h3>
    </header>
    {% for cat in category_count %}
    <div class="item d-flex justify-content-between">
      <a href="#">{{ cat.categories__title }}</a><span>{{ cat.categories__title__count }}</span>
    </div>
    {% endfor %}
  </div>
  <!-- Widget [Tags Cloud Widget]-->
  <div class="widget tags">       
    <header>
      <h3 class="h6">Gooogle adsense will be here</h3>
    </header>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#" class="tag">#Business</a></li>
      <li class="list-inline-item"><a href="#" class="tag">#Technology</a></li>
      <li class="list-inline-item"><a href="#" class="tag">#Fashion</a></li>
      <li class="list-inline-item"><a href="#" class="tag">#Sports</a></li>
      <li class="list-inline-item"><a href="#" class="tag">#Economy</a></li>
    </ul>
  </div>
</aside>